// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt4TfSW8_fwm9KTKkdCcsgZn1M5GOsGjg',
    appId: '1:961755534684:web:db4b22a64fcfe29180dd99',
    messagingSenderId: '961755534684',
    projectId: 'insta123-d98a7',
    authDomain: 'insta123-d98a7.firebaseapp.com',
    storageBucket: 'insta123-d98a7.firebasestorage.app',
    measurementId: 'G-SZK0M5GP80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDmbJoGjVbFX9uVX48WSdd7U6skDDRhiQ',
    appId: '1:961755534684:android:72b89aac8cff96d380dd99',
    messagingSenderId: '961755534684',
    projectId: 'insta123-d98a7',
    storageBucket: 'insta123-d98a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcOHLzZ-cHOuv8ysnV8NXvaPK05Eh0lbg',
    appId: '1:961755534684:ios:f947f9af8dac98e980dd99',
    messagingSenderId: '961755534684',
    projectId: 'insta123-d98a7',
    storageBucket: 'insta123-d98a7.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcOHLzZ-cHOuv8ysnV8NXvaPK05Eh0lbg',
    appId: '1:961755534684:ios:f947f9af8dac98e980dd99',
    messagingSenderId: '961755534684',
    projectId: 'insta123-d98a7',
    storageBucket: 'insta123-d98a7.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt4TfSW8_fwm9KTKkdCcsgZn1M5GOsGjg',
    appId: '1:961755534684:web:c54b0b6f0fb56f8b80dd99',
    messagingSenderId: '961755534684',
    projectId: 'insta123-d98a7',
    authDomain: 'insta123-d98a7.firebaseapp.com',
    storageBucket: 'insta123-d98a7.firebasestorage.app',
    measurementId: 'G-W07NT65C8J',
  );
}
